name: CI/CD using GitHub Actions

# event trigger
# develop/main 브랜치에 push 혹은 pull_request가 되었을 때 실행
on:
  push:
    branches: [ "develop/main" ]
  pull_request:
    branches: [ "develop/main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # 기본 체크아웃
    - name: Checkout
      uses: actions/checkout@v4
      
    # JDK 17 세팅
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    # prod 설정
    - name: make application-prod.yml
      run: |
        cd ./src/main/resources
        touch ./application-prod.yml
        echo "${{ secrets.YML_PROD }}" > ./application-prod.yml
      shell: bash

    # gradle build
    - name: Build with Gradle
      run: ./gradlew build -x test
